version: "3"

services:
  kafka1:
    image: confluentinc/cp-kafka:7.5.2
    container_name: kafka1
    ports: [ "9092:9092" ]
    env_file:
      - '.env'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: CONTROLLER://kafka1:29093,INTERNAL://kafka1:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://localhost:9092
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:29093,2@kafka2:29093,3@kafka3:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_LISTENER_NAME_INTERNAL_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="${USERNAME}" \
        password="${PASSWORD}" \
        user_admin="${USER_ADMIN}" \
        user_client="${USER_CLIENT}";
      KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="${USERNAME}" \
        password="${PASSWORD}" \
        user_admin="${USER_ADMIN}" \
        user_client="${USER_CLIENT}";

  kafka2:
    image: confluentinc/cp-kafka:7.5.2
    container_name: kafka2
    ports: [ "9093:9092" ]
    env_file:
      - '.env'
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: CONTROLLER://kafka2:29093,INTERNAL://kafka2:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:29092,EXTERNAL://localhost:9092
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:29093,2@kafka2:29093,3@kafka3:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_LISTENER_NAME_INTERNAL_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="${USERNAME}" \
        password="${PASSWORD}" \
        user_admin="${USER_ADMIN}" \
        user_client="${USER_CLIENT}";
      KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="${USERNAME}" \
        password="${PASSWORD}" \
        user_admin="${USER_ADMIN}" \
        user_client="${USER_CLIENT}";
  kafka3:
    image: confluentinc/cp-kafka:7.5.2
    container_name: kafka3
    ports: [ "9094:9092" ]
    env_file:
      - '.env'
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: CONTROLLER://kafka3:29093,INTERNAL://kafka3:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:29092,EXTERNAL://localhost:9092
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:29093,2@kafka2:29093,3@kafka3:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_LISTENER_NAME_INTERNAL_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="${USERNAME}" \
        password="${PASSWORD}" \
        user_admin="${USER_ADMIN}" \
        user_client="${USER_CLIENT}";
      KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="${USERNAME}" \
        password="${PASSWORD}" \
        user_admin="${USER_ADMIN}" \
        user_client="${USER_CLIENT}";
  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.2
    container_name: schema-registry
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports: [ "8081:8081" ]
    env_file:
      - '.env'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka1:29092,kafka2:29092,kafka3:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_PLAINTEXT
      SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: PLAIN
      SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="client" \
        password="${USER_CLIENT}";
      # command:
      #   - sh
      #   - -c
      #   - |
      #     echo 'KafkaClient {
      #       org.apache.kafka.common.security.plain.PlainLoginModule required
      #       username="client"
      #       password="${USER_CLIENT}";
      #     };' > /etc/schema-registry/kafka_client_jaas.conf
      #     /etc/confluent/docker/run
      # SCHEMA_REGISTRY_OPTS: -Djava.security.auth.login.config=/etc/schema-registry/kafka_client_jaas.conf

