version: "3"

services:
  broker1:
    image: confluentinc/cp-kafka:7.5.2
    container_name: $BROKER1
    hostname: $BROKER1
    ports: [ "9092:9092" ]
    env_file:
      - '.env'
    environment:
      KAFKA_NODE_ID: $ID1
      KAFKA_LISTENERS: CONTROLLER://$BROKER1:29093,INTERNAL://$BROKER1:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://$BROKER1:29092,EXTERNAL://localhost:9092
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: $ID1@$BROKER1:29093,$ID2@$BROKER2:29093,$ID3@$BROKER3:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:SASL_SSL,EXTERNAL:SASL_SSL
      BROKER: $BROKER1
    volumes:
      - $SC_DIR/$BROKER1:/etc/kafka/secrets
      - ./init/broker.sh:/etc/init.sh
      - $CA_CERT:/etc/ca/ca.crt
    command:
      - sh 
      - -c
      - cd /etc/ && ./init.sh
  broker2:
    image: confluentinc/cp-kafka:7.5.2
    container_name: $BROKER2
    hostname: $BROKER2
    ports: [ "9093:9092" ]
    env_file:
      - '.env'
    environment:
      KAFKA_NODE_ID: $ID2
      KAFKA_LISTENERS: CONTROLLER://$BROKER2:29093,INTERNAL://$BROKER2:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://$BROKER2:29092,EXTERNAL://localhost:9092
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: $ID1@$BROKER1:29093,$ID2@$BROKER2:29093,$ID3@$BROKER3:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:SASL_SSL,EXTERNAL:SASL_SSL
      BROKER: $BROKER2
    volumes:
      - $SC_DIR/$BROKER2:/etc/kafka/secrets
      - ./init/broker.sh:/etc/init.sh
      - $CA_CERT:/etc/ca/ca.crt
    command:
      - sh 
      - -c
      - cd /etc/ && ./init.sh

  broker3:
    image: confluentinc/cp-kafka:7.5.2
    container_name: $BROKER3
    hostname: $BROKER3
    ports: [ "9094:9092" ]
    env_file:
      - '.env'
    environment:
      KAFKA_NODE_ID: $ID3
      KAFKA_LISTENERS: CONTROLLER://$BROKER3:29093,INTERNAL://$BROKER3:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://$BROKER3:29092,EXTERNAL://localhost:9092
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: $ID1@$BROKER1:29093,$ID2@$BROKER2:29093,$ID3@$BROKER3:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:SASL_SSL,EXTERNAL:SASL_SSL
      BROKER: $BROKER3
    volumes:
      - $SC_DIR/$BROKER3:/etc/kafka/secrets
      - ./init/broker.sh:/etc/init.sh
      - $CA_CERT:/etc/ca/ca.crt
    command:
      - sh 
      - -c
      - cd /etc/ && ./init.sh
  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.2
    container_name: $SR_HOST
    hostname: $SR_HOST
    depends_on:
      - broker1
      - broker2
      - broker3
    ports: [ "8081:8081" ]
    env_file:
      - '.env'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: $BROKER1:29092,$BROKER2:29092,$BROKER3:29092 
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_SSL
      SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: PLAIN
    volumes:
      - $CA_CERT:/etc/ca/ca.crt
      - ./init/registry.sh:/etc/init.sh
    command:
      - sh 
      - -c
      - cd /etc/ && ./init.sh
